#!/usr/bin/env ruby -w
require 'time'
require 'rake'

File.open("run_each_spec_in_isolation.txt", 'w+') do |file|
  FileList['spec/**/*_spec.rb'].sort.select do |fn|
    start_time = Time.now
    puts "rspec #{fn}"
    system "rspec #{fn}"
    end_time = Time.now
    file.puts format("%#.3g\t%s", (end_time - start_time), fn)
  end
end