#!/usr/bin/env ruby -w
require 'time'
require 'rake'

failed_result = false
FileList['spec/**/*_spec.rb'].sort.select do |fn|
  puts "rspec #{fn}"
  failed_result ||= !(system "rspec #{fn}")
end
failed_result ||= !(system('rspec'))

if failed_result
  STDERR.puts "Error encountered in isolation tests."
  exit!(-1)
else
  STDOUT.puts "Success"
  exit!(0)
end
